# Server
server:
  address: 0.0.0.0
  port: 8082
  servlet:
    context-path: /okr

# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/okr_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Jackson
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false